INSERT INTO Genres (id, name) VALUES (1, 'Silent');
INSERT INTO Genres (id, name) VALUES (2, 'Short');
INSERT INTO Genres (id, name) VALUES (3, 'Documentary');
INSERT INTO Genres (id, name) VALUES (4, 'Comedy');
INSERT INTO Genres (id, name) VALUES (5, 'Fantasy');
INSERT INTO Genres (id, name) VALUES (6, 'Western');
INSERT INTO Genres (id, name) VALUES (7, 'Crime');
INSERT INTO Genres (id, name) VALUES (8, 'Drama');
INSERT INTO Genres (id, name) VALUES (9, 'Adventure');
INSERT INTO Genres (id, name) VALUES (10, 'Romance');
INSERT INTO Genres (id, name) VALUES (11, 'Action');
INSERT INTO Genres (id, name) VALUES (12, 'Animated');
INSERT INTO Genres (id, name) VALUES (13, 'Historical');
INSERT INTO Genres (id, name) VALUES (14, 'Biography');
INSERT INTO Genres (id, name) VALUES (15, 'Horror');
INSERT INTO Genres (id, name) VALUES (16, 'War');
INSERT INTO Genres (id, name) VALUES (17, 'Mystery');
INSERT INTO Genres (id, name) VALUES (18, 'Thriller');
INSERT INTO Genres (id, name) VALUES (19, 'Sports');
INSERT INTO Genres (id, name) VALUES (20, 'Musical');
INSERT INTO Genres (id, name) VALUES (21, 'Teen');
INSERT INTO Genres (id, name) VALUES (22, 'Sport');
INSERT INTO Genres (id, name) VALUES (23, 'Family');
INSERT INTO Genres (id, name) VALUES (24, 'Independent');
INSERT INTO Genres (id, name) VALUES (25, 'Spy');
INSERT INTO Genres (id, name) VALUES (26, 'Satire');
INSERT INTO Genres (id, name) VALUES (27, 'Erotic');
INSERT INTO Genres (id, name) VALUES (28, 'Science Fiction');
INSERT INTO Genres (id, name) VALUES (29, 'Dance');
INSERT INTO Genres (id, name) VALUES (30, 'Disaster');
INSERT INTO Genres (id, name) VALUES (31, 'Noir');
INSERT INTO Genres (id, name) VALUES (32, 'Supernatural');
INSERT INTO Genres (id, name) VALUES (33, 'Political');
INSERT INTO Genres (id, name) VALUES (34, 'Suspense');
INSERT INTO Genres (id, name) VALUES (35, 'Superhero');
INSERT INTO Genres (id, name) VALUES (36, 'Live Action');
INSERT INTO Genres (id, name) VALUES (37, 'Legal');
INSERT INTO Genres (id, name) VALUES (38, 'Performance');
INSERT INTO Genres (id, name) VALUES (39, 'Slasher');
INSERT INTO Genres (id, name) VALUES (40, 'Martial Arts');
INSERT INTO Genres (id, name) VALUES (41, 'Found Footage');
